export const product = [
  {name: 'PSYCHO', category: 1, imgSrc: ''},
  {name: 'Power Source', category: 1, imgSrc: ''},
  {name: 'Death Coming', category: 1, imgSrc: ''},
  {name: 'New Terror', category: 1, imgSrc: ''},
  {name: 'Zombie', category: 3, imgSrc: ''},
  {name: 'Zombie', category: 1, imgSrc: ''},
  {name: 'Digital Slavery', category: 2, imgSrc: ''},
  {name: 'Desires', category: 1, imgSrc: ''},
  {name: 'Digital Slavery', category: 3, imgSrc: ''},
  {name: 'KILL', category: 1, imgSrc: ''},
  {name: 'Terror', category: 1, imgSrc: ''},
  {name: 'Met Basic', category: 1, imgSrc: ''},
  {name: 'Motel White', category: 1, imgSrc: ''},
  {name: 'Acid', category: 1, imgSrc: ''},
  {name: 'Motel Black', category: 1, imgSrc: ''},
  {name: 'Met', category: 3, imgSrc: ''},
  {name: 'Dead', category: 3, imgSrc: ''},
  {name: 'Suspiria', category: 1, imgSrc: ''},
  {name: 'PSYCHO', category: 3, imgSrc: ''},
  {name: 'Nothing', category: 2, imgSrc: ''},
  {name: 'Living Dead', category: 1, imgSrc: ''},
  {name: 'Virtual World', category: 1, imgSrc: ''},
  {name: 'Craw', category: 1, imgSrc: ''},
  {name: 'Simulated', category: 1, imgSrc: ''},
  {name: 'Basic Blue', category: 1, imgSrc: ''},
  {name: 'Atomic', category: 1, imgSrc: ''},
  {name: 'Fantazia', category: 1, imgSrc: ''},
  {name: 'Craw', category: 3, imgSrc: ''},
  {name: 'Neuro', category: 1, imgSrc: ''},
  {name: 'Basic Red', category: 1, imgSrc: ''},
  {name: 'Demon Black', category: 1, imgSrc: ''},
  {name: 'Digital Slavery', category: 2, imgSrc: ''},
]
